### PR TITLE
Initial OpenSSL 3.0 support

### LINKED ISSUE #1212: 2.1.12: test suite is failing (with openssl 3.0)
I've started using openssl and I;ve noticed that after that test suite is failing
```console
+ cd libevent-2.1.12-stable
+ /usr/bin/make -O -j48 V=1 VERBOSE=1 check
/usr/bin/make  check-am
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
echo "Rename man pages in ./doxygen/man/man3/"
Rename man pages in ./doxygen/man/man3/
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
/usr/bin/make  check-TESTS
make[3]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
./test/test.sh -b EVPORT
Running tests:
EVPORT
Skipping test
make[3]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
make[3]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
./test/test.sh -b KQUEUE
Running tests:
KQUEUE
Skipping test
make[3]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
make[3]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
./test/test.sh -b WIN32
Running tests:
WIN32
Skipping test
make[3]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
make[3]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
./test/test.sh -b DEVPOLL
Running tests:
DEVPOLL
Skipping test
make[3]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
make[3]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
PASS: test_runner_evport
make[3]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
make[3]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
PASS: test_runner_kqueue
make[3]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
make[3]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
PASS: test_runner_win32
make[3]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
make[3]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
PASS: test_runner_devpoll
make[3]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
make[3]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
./test/test.sh -b "" -t
Running tests:
EPOLL (timerfd)
 test-eof: OKAY
 test-closed: OKAY
 test-weof: OKAY
 test-time: OKAY
 test-changelist: OKAY
 test-fdleak: OKAY
 test-dumpevents: OKAY
 regress:
  FAIL test/regress_http.c:3154: assert(test_ok == 2): -2 vs 2http/https_incomplete:
  [https_incomplete FAILED]

  FAIL test/regress_http.c:3154: assert(test_ok == 2): -2 vs 2http/https_incomplete_timeout:
  [https_incomplete_timeout FAILED]

  FAIL test/regress_http.c:3363: assert(test_ok == 2): -1 vs 2http/https_chunk_out:
  [https_chunk_out FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_dirty_shutdown:
  [bufferevent_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_renegotiate_socketpair_dirty_shutdown:
  [bufferevent_renegotiate_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_startopen_dirty_shutdown:
  [bufferevent_socketpair_startopen_dirty_shutdown FAILED]
6/324 TESTS FAILED. (27 skipped)
FAILED
 regress_debug:
  FAIL test/regress_http.c:3154: assert(test_ok == 2): -2 vs 2http/https_incomplete:
  [https_incomplete FAILED]

  FAIL test/regress_http.c:3154: assert(test_ok == 2): -2 vs 2http/https_incomplete_timeout:
  [https_incomplete_timeout FAILED]

  FAIL test/regress_http.c:3363: assert(test_ok == 2): -1 vs 2http/https_chunk_out:
  [https_chunk_out FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_dirty_shutdown:
  [bufferevent_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_renegotiate_socketpair_dirty_shutdown:
  [bufferevent_renegotiate_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_startopen_dirty_shutdown:
  [bufferevent_socketpair_startopen_dirty_shutdown FAILED]
6/324 TESTS FAILED. (27 skipped)
FAILED
make[3]: *** [Makefile:3133: test_runner_timerfd] Error 1
make[3]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
make[3]: *** Waiting for unfinished jobs....
make[3]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
./test/test.sh -b SELECT
Running tests:
SELECT
 test-eof: OKAY
 test-closed: [warn] event_base_new_with_config: no event mechanism available
OKAY
 test-weof: OKAY
 test-time: OKAY
 test-changelist: OKAY
 test-fdleak: OKAY
 test-dumpevents: OKAY
 regress:
  FAIL test/regress_http.c:3154: assert(test_ok == 2): -2 vs 2http/https_incomplete:
  [https_incomplete FAILED]

  FAIL test/regress_http.c:3154: assert(test_ok == 2): -2 vs 2http/https_incomplete_timeout:
  [https_incomplete_timeout FAILED]

  FAIL test/regress_http.c:3363: assert(test_ok == 2): -1 vs 2http/https_chunk_out:
  [https_chunk_out FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_dirty_shutdown:
  [bufferevent_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_renegotiate_socketpair_dirty_shutdown:
  [bufferevent_renegotiate_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_startopen_dirty_shutdown:
  [bufferevent_socketpair_startopen_dirty_shutdown FAILED]
6/315 TESTS FAILED. (36 skipped)
FAILED
 regress_debug:
  FAIL test/regress_http.c:3154: assert(test_ok == 2): -2 vs 2http/https_incomplete:
  [https_incomplete FAILED]

  FAIL test/regress_http.c:3154: assert(test_ok == 2): -2 vs 2http/https_incomplete_timeout:
  [https_incomplete_timeout FAILED]

  FAIL test/regress_http.c:3363: assert(test_ok == 2): -1 vs 2http/https_chunk_out:
  [https_chunk_out FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_dirty_shutdown:
  [bufferevent_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_renegotiate_socketpair_dirty_shutdown:
  [bufferevent_renegotiate_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_startopen_dirty_shutdown:
  [bufferevent_socketpair_startopen_dirty_shutdown FAILED]
6/315 TESTS FAILED. (36 skipped)
FAILED
make[3]: *** [Makefile:3121: test_runner_select] Error 1
make[3]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
make[3]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
./test/test.sh -b "" -T
Running tests:
EPOLL (timerfd+changelist)
 test-eof: OKAY
 test-closed: OKAY
 test-weof: OKAY
 test-time: OKAY
 test-changelist: OKAY
 test-fdleak: OKAY
 test-dumpevents: OKAY
 regress:
  FAIL test/regress_http.c:3154: assert(test_ok == 2): -2 vs 2http/https_incomplete:
  [https_incomplete FAILED]

  FAIL test/regress_http.c:3154: assert(test_ok == 2): -2 vs 2http/https_incomplete_timeout:
  [https_incomplete_timeout FAILED]

  FAIL test/regress_http.c:3363: assert(test_ok == 2): -1 vs 2http/https_chunk_out:
  [https_chunk_out FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_dirty_shutdown:
  [bufferevent_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_renegotiate_socketpair_dirty_shutdown:
  [bufferevent_renegotiate_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_startopen_dirty_shutdown:
  [bufferevent_socketpair_startopen_dirty_shutdown FAILED]
6/324 TESTS FAILED. (27 skipped)
FAILED
 regress_debug:
  FAIL test/regress_http.c:3154: assert(test_ok == 2): -2 vs 2http/https_incomplete:
  [https_incomplete FAILED]

  FAIL test/regress_http.c:3154: assert(test_ok == 2): -2 vs 2http/https_incomplete_timeout:
  [https_incomplete_timeout FAILED]

  FAIL test/regress_http.c:3363: assert(test_ok == 2): -1 vs 2http/https_chunk_out:
  [https_chunk_out FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_dirty_shutdown:
  [bufferevent_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_renegotiate_socketpair_dirty_shutdown:
  [bufferevent_renegotiate_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_startopen_dirty_shutdown:
  [bufferevent_socketpair_startopen_dirty_shutdown FAILED]
6/324 TESTS FAILED. (27 skipped)
FAILED
make[3]: *** [Makefile:3137: test_runner_timerfd_changelist] Error 1
make[3]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
make[3]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
./test/test.sh -b POLL
Running tests:
POLL
 test-eof: OKAY
 test-closed: OKAY
 test-weof: OKAY
 test-time: OKAY
 test-changelist: OKAY
 test-fdleak: OKAY
 test-dumpevents: OKAY
 regress:
  FAIL test/regress_http.c:3154: assert(test_ok == 2): -2 vs 2http/https_incomplete:
  [https_incomplete FAILED]

  FAIL test/regress_http.c:3154: assert(test_ok == 2): -2 vs 2http/https_incomplete_timeout:
  [https_incomplete_timeout FAILED]

  FAIL test/regress_http.c:3363: assert(test_ok == 2): -1 vs 2http/https_chunk_out:
  [https_chunk_out FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_dirty_shutdown:
  [bufferevent_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_renegotiate_socketpair_dirty_shutdown:
  [bufferevent_renegotiate_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_startopen_dirty_shutdown:
  [bufferevent_socketpair_startopen_dirty_shutdown FAILED]
6/320 TESTS FAILED. (31 skipped)
FAILED
 regress_debug:
  FAIL test/regress_http.c:3154: assert(test_ok == 2): -2 vs 2http/https_incomplete:
  [https_incomplete FAILED]

  FAIL test/regress_http.c:3154: assert(test_ok == 2): -2 vs 2http/https_incomplete_timeout:
  [https_incomplete_timeout FAILED]

  FAIL test/regress_http.c:3363: assert(test_ok == 2): -1 vs 2http/https_chunk_out:
  [https_chunk_out FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_dirty_shutdown:
  [bufferevent_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_renegotiate_socketpair_dirty_shutdown:
  [bufferevent_renegotiate_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_startopen_dirty_shutdown:
  [bufferevent_socketpair_startopen_dirty_shutdown FAILED]
6/320 TESTS FAILED. (31 skipped)
FAILED
make[3]: *** [Makefile:3129: test_runner_poll] Error 1
make[3]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
make[3]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
./test/test.sh -b "" -c
Running tests:
EPOLL (changelist)
 test-eof: OKAY
 test-closed: OKAY
 test-weof: OKAY
 test-time: OKAY
 test-changelist: OKAY
 test-fdleak: OKAY
 test-dumpevents: OKAY
 regress:
  FAIL test/regress_http.c:3154: assert(test_ok == 2): -2 vs 2http/https_incomplete:
  [https_incomplete FAILED]

  FAIL test/regress_http.c:3154: assert(test_ok == 2): -2 vs 2http/https_incomplete_timeout:
  [https_incomplete_timeout FAILED]

  FAIL test/regress_http.c:3363: assert(test_ok == 2): -1 vs 2http/https_chunk_out:
  [https_chunk_out FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_dirty_shutdown:
  [bufferevent_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_renegotiate_socketpair_dirty_shutdown:
  [bufferevent_renegotiate_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_startopen_dirty_shutdown:
  [bufferevent_socketpair_startopen_dirty_shutdown FAILED]
6/324 TESTS FAILED. (27 skipped)
FAILED
 regress_debug:
  FAIL test/regress_http.c:3154: assert(test_ok == 2): -2 vs 2http/https_incomplete:
  [https_incomplete FAILED]

  FAIL test/regress_http.c:3154: assert(test_ok == 2): -2 vs 2http/https_incomplete_timeout:
  [https_incomplete_timeout FAILED]

  FAIL test/regress_http.c:3363: assert(test_ok == 2): -1 vs 2http/https_chunk_out:
  [https_chunk_out FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_dirty_shutdown:
  [bufferevent_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_renegotiate_socketpair_dirty_shutdown:
  [bufferevent_renegotiate_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_startopen_dirty_shutdown:
  [bufferevent_socketpair_startopen_dirty_shutdown FAILED]
6/324 TESTS FAILED. (27 skipped)
FAILED
make[3]: *** [Makefile:3135: test_runner_changelist] Error 1
make[3]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
make[3]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
./test/test.sh -b EPOLL
Running tests:
EPOLL
 test-eof: OKAY
 test-closed: OKAY
 test-weof: OKAY
 test-time: OKAY
 test-changelist: OKAY
 test-fdleak: OKAY
 test-dumpevents: OKAY
 regress:
  FAIL test/regress_http.c:3154: assert(test_ok == 2): -2 vs 2http/https_incomplete:
  [https_incomplete FAILED]

  FAIL test/regress_http.c:3154: assert(test_ok == 2): -2 vs 2http/https_incomplete_timeout:
  [https_incomplete_timeout FAILED]

  FAIL test/regress_http.c:3363: assert(test_ok == 2): -1 vs 2http/https_chunk_out:
  [https_chunk_out FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_dirty_shutdown:
  [bufferevent_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_renegotiate_socketpair_dirty_shutdown:
  [bufferevent_renegotiate_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_startopen_dirty_shutdown:
  [bufferevent_socketpair_startopen_dirty_shutdown FAILED]
6/324 TESTS FAILED. (27 skipped)
FAILED
 regress_debug:
  FAIL test/regress_http.c:3154: assert(test_ok == 2): -2 vs 2http/https_incomplete:
  [https_incomplete FAILED]

  FAIL test/regress_http.c:3154: assert(test_ok == 2): -2 vs 2http/https_incomplete_timeout:
  [https_incomplete_timeout FAILED]

  FAIL test/regress_http.c:3363: assert(test_ok == 2): -1 vs 2http/https_chunk_out:
  [https_chunk_out FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_dirty_shutdown:
  [bufferevent_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_renegotiate_socketpair_dirty_shutdown:
  [bufferevent_renegotiate_socketpair_dirty_shutdown FAILED]

  FAIL test/regress_ssl.c:538: assert(got_close == 1): 0 vs 1ssl/bufferevent_socketpair_startopen_dirty_shutdown:
  [bufferevent_socketpair_startopen_dirty_shutdown FAILED]
6/324 TESTS FAILED. (27 skipped)
FAILED
make[3]: *** [Makefile:3119: test_runner_epoll] Error 1
make[3]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libevent-2.1.12-stable'
make[2]: *** [Makefile:2521: check-TESTS] Error 2
make[1]: *** [Makefile:2796: check-am] Error 2
make: *** [Makefile:2798: check] Error 2
```

### PR DESCRIPTION
**Pull request by lux01**
* Don't use deprecated functions when building against OpenSSL 3.0.
* Recognise that OpenSSL 3.0 can signal a dirty shutdown as a protocol error in addition to the expected IO error produced by OpenSSL 1.1.1.
* Add missing strndup function on Windows to make https-client sample build on Windows with MSVC 2022.

This fixes #1212 and #1233 in my testing on Ubuntu 20.04 WSL with GCC 9 and on Windows 11 with MSVC 2022, both using the latest commit [`8547cd6790881cbba0f20aa4ce048243065a24bf` from the master branch of OpenSSL](https://github.com/openssl/openssl/tree/8547cd6790881cbba0f20aa4ce048243065a24bf)

Fixes: #1212 
Fixes: #1233 
Fixes: #1250

### CODE REVIEW

**Review by azat — APPROVED** [review]
LGTM, thanks! Maybe you can also add ubuntu with openssl 3.0 to the build matrix?

- https://github.com/libevent/libevent/blob/1c204d55640170b77ed2f7e8cc07f9417e1844cc/.github/workflows/linux.yml#L33
- https://github.com/libevent/libevent/blob/1c204d55640170b77ed2f7e8cc07f9417e1844cc/.github/workflows/linux.yml#L157

**Comment by lux01** [comment]
I've had a stab at adding OpenSSL 3 to the Linux build matrix, but I must admit I've not worked with GitHub actions before so I'll keep my fingers crossed. I'm not sure what's going on with the other workflows, I don't see why my changes would break the macOS/Windows builds in the ways that they are.

**Comment by azat** [comment]
@lux01 there are [some failures](https://github.com/libevent/libevent/runs/6960322791?check_suite_focus=true) for OpenSSL 3.0, can you please take a look?

**Comment by loqs** [comment]
```
2022-06-20T04:15:22.6251913Z /home/runner/work/libevent/libevent/test/regress_mbedtls.c:49:0: warning: "SSL_get_peer_certificate" redefined
2022-06-20T04:15:22.6252695Z  #define SSL_get_peer_certificate mbedtls_ssl_get_peer_cert
2022-06-20T04:15:22.6253290Z  
2022-06-20T04:15:22.6255663Z In file included from /home/runner/work/libevent/libevent/test/regress.h:139:0,
2022-06-20T04:15:22.6256872Z                  from /home/runner/work/libevent/libevent/test/regress_mbedtls.c:34:
2022-06-20T04:15:22.6259090Z /tmp/openssl-3/install/include/openssl/ssl.h:1792:0: note: this is the location of the previous definition
2022-06-20T04:15:22.6259878Z  #   define SSL_get_peer_certificate SSL_get1_peer_certificate
2022-06-20T04:15:22.6261034Z  
2022-06-20T04:15:22.6357093Z In file included from /home/runner/work/libevent/libevent/test/regress_mbedtls.c:77:0:
2022-06-20T04:15:22.6358885Z /home/runner/work/libevent/libevent/test/regress_ssl.c: In function ‘eventcb’:
2022-06-20T04:15:22.6384982Z /home/runner/work/libevent/libevent/test/regress_ssl.c:232:41: warning: passing argument 1 of ‘SSL_get1_peer_certificate’ from incompatible pointer type [-Wincompatible-pointer-types]
2022-06-20T04:15:22.6385614Z    peer_cert = SSL_get1_peer_certificate(ssl);
2022-06-20T04:15:22.6385899Z                                          ^~~
2022-06-20T04:15:22.6386460Z In file included from /home/runner/work/libevent/libevent/test/regress.h:139:0,
2022-06-20T04:15:22.6387109Z                  from /home/runner/work/libevent/libevent/test/regress_mbedtls.c:34:
2022-06-20T04:15:22.6387913Z /tmp/openssl-3/install/include/openssl/ssl.h:1789:14: note: expected ‘const SSL * {aka const struct ssl_st *}’ but argument is of type ‘mbedtls_ssl_context * {aka struct mbedtls_ssl_context *}’
2022-06-20T04:15:22.6388400Z  __owur X509 *SSL_get1_peer_certificate(const SSL *s);
2022-06-20T04:15:22.6388676Z               ^~~~~~~~~~~~~~~~~~~~~~~~~
2022-06-20T04:15:22.6389053Z In file included from /home/runner/work/libevent/libevent/test/regress_mbedtls.c:77:0:
2022-06-20T04:15:22.6389875Z /home/runner/work/libevent/libevent/test/regress_ssl.c:232:13: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
2022-06-20T04:15:22.6390320Z    peer_cert = SSL_get1_peer_certificate(ssl);
```
test/regress_mbedtls.c includes regress_ssl.c when both OpenSSL3 and mbedtls are in use so SSL_get1_peer_certificate is used but the ssl object is an mbedtls_ssl_context.

**Comment by lux01** [comment]
I didn't realise that the Mbed-TLS testing worked this way. I didn't have Mbed-TLS installed on my machine when I made the original changes. I've built that now too and have pushed a change that appears to work for me with Mbed-TLS 2.28.0.

As an aside, I originally tried Mbed-TLS 3.1.0 but it looks like libevent doesn't support that yet? FindMbedTLS.cmake at least looks in mbedtls/version.h for the MBEDTLS_VERSION_xxx version macros but in 3.x they're in mbedtls/build_info.h. I didn't try any further with 3.1.0 and switched to 2.28.0

**Comment by lux01** [comment]
So it does look like Mbed-TLS 3.0 support is blocking the bulk of the currently failing tests. I've pushed a new change that gets libevent building (and passing on my machine) with Mbed-TLS 3.1.0 and 2.28.0. Let's see how this goes...

File: bufferevent_openssl.c [hunk 1]
```diff
@@ -259,7 +259,9 @@ conn_closed(struct bufferevent_ssl *bev_ssl, int when, int errcode, int ret)
 		bufferevent_ssl_put_error(bev_ssl, errcode);
 		break;
 	case SSL_ERROR_SSL:
-		/* Protocol error. */
+		/* Protocol error; possibly a dirty shutdown. */
```
Comment (peadar) [inline bufferevent_openssl.c:262]: I started looking at this independently before I found this pull request, and came up with a slightly different formulation to fix this. 
SSL_ERROR_SSL is not guaranteed to indicate that a system call has failed, so looking at "ret" does not reliably indicate that a read call has given an EOF -  it's possibly better to look at the error code here to ensure that it's caused by an EOF on a read:

```
diff --git a/bufferevent_openssl.c b/bufferevent_openssl.c
index 6ace1e3a..5bdda402 100644
--- a/bufferevent_openssl.c
+++ b/bufferevent_openssl.c
@@ -259,6 +259,18 @@ conn_closed(struct bufferevent_ssl *bev_ssl, int when, int errcode, int ret)
                bufferevent_ssl_put_error(bev_ssl, errcode);
                break;
        case SSL_ERROR_SSL:
+#ifdef SSL_R_UNEXPECTED_EOF_WHILE_READING
+               err = ERR_peek_error();
+               if (ERR_GET_LIB(err) == ERR_LIB_SSL &&
+                   ERR_GET_REASON(err) == SSL_R_UNEXPECTED_EOF_WHILE_READING) {
+                       /* Possibly a clean shutdown. */
+                       if (SSL_get_shutdown(bev_ssl->ssl) & SSL_RECEIVED_SHUTDOWN)
+                               event = BEV_EVENT_EOF;
+                       else
+                               dirty_shutdown = 1;
+                       break;
+               }
+#endif
```

File: sample/becat.c [hunk 2]
```diff
@@ -188,6 +188,10 @@ static void ssl_ctx_free(struct ssl_context *ssl)
 static int ssl_load_key(struct ssl_context *ssl)
 {
 	int err = 1;
+#if OPENSSL_VERSION_MAJOR >= 3
```
Comment (peadar) [inline sample/becat.c:191]: I don't think OpenSSL 1.x defines OPENSSL_VERSION_MAJOR - you might need
OPENSSL_VERSION_NUMBER >= 0x30000000

**Comment by azat** [comment]
@lux01 I've applied `strndup` from your PR separately and will rebase your PR on top of upstream now by myself.

File: sample/becat.c (hunk 2 above)
Comment (azat) [reply sample/becat.c:191]: Indeed, nice catch.

Also CI reports:

```
2022-06-23T08:16:11.2428545Z ../sample/le-proxy.c:116:5: warning: "OPENSSL_VERSION_MAJOR" is not defined, evaluates to 0 [-Wundef]
2022-06-23T08:16:11.2429120Z  #if OPENSSL_VERSION_MAJOR >= 3
```

I will add `-Werror` on CI - #1297

File: .github/workflows/linux.yml [hunk 3]
```diff
@@ -178,6 +208,32 @@ jobs:
...
+            make -j ${JOBS}
+            make install
+            cd install
+            if [ ! -d lib ]; then
+              ln -s lib64 lib
+            fi
+
+            echo [openssl-${OPENSSL_VERSION}]: Installed to $PWD/install
+            popd
+          fi
```
Comment (azat) [inline .github/workflows/linux.yml:235]: It is OK for now, although it is simpler to use ubuntu:22 that has openssl 3.

File: mbedtls-compat.h [hunk 4]
```diff
@@ -2,6 +2,9 @@
 #define MBEDTLS_COMPAT_H
 
 #include <mbedtls/version.h>
+#if MBEDTLS_VERSION_MAJOR >= 3
+#include <mbedtls/compat-2.x.h>
```
Comment (azat) [inline mbedtls-compat.h:6]: It seems that it is deprecated:

```
2022-06-28T08:10:49.5535357Z D:/a/_temp/msys64/mingw64/include/mbedtls/compat-2.x.h:26:2: warning: #warning "Including compat-2.x.h is deprecated" [-Wcpp]
2022-06-28T08:10:49.6105073Z    26 | #warning "Including compat-2.x.h is deprecated"
```

But it is OK for now.

File: bufferevent_openssl.c (hunk 1 above)
Comment (azat) [reply bufferevent_openssl.c:262]: This looks better, will apply your hunk, thanks!

Comment (azat) [reply bufferevent_openssl.c:262]: By the way, @peadar maybe we should check here for `SSL_R_TLSV1_ALERT_DECODE_ERROR`, as suggested by @loqs here https://github.com/libevent/libevent/issues/1250#issuecomment-1097249859, what do you think?

File: mbedtls-compat.h [hunk 5]
```diff
@@ -2,6 +2,9 @@
 #define MBEDTLS_COMPAT_H
 
 #include <mbedtls/version.h>
+#if MBEDTLS_VERSION_MAJOR >= 3
```
Comment (azat) [inline mbedtls-compat.h:5]:
```
2022-06-28T07:59:35.5912214Z ../test/regress_mbedtls.c: In function ‘mbedtls_getkey’:
2022-06-28T07:59:35.5913141Z ../test/regress_mbedtls.c:119:5: warning: "MBEDTLS_VERSION_MAJOR" is not defined, evaluates to 0 [-Wundef]
2022-06-28T07:59:35.5913512Z  #if MBEDTLS_VERSION_MAJOR >= 3
2022-06-28T07:59:35.5913766Z      ^~~~~~~~~~~~~~~~~~~~~
2022-06-28T07:59:35.5938058Z ../test/regress_mbedtls.c: In function ‘get_mbedtls_config’:
2022-06-28T07:59:35.5942081Z ../test/regress_mbedtls.c:234:5: warning: "MBEDTLS_VERSION_MAJOR" is not defined, evaluates to 0 [-Wundef]
2022-06-28T07:59:35.5942977Z  #if MBEDTLS_VERSION_MAJOR < 3
2022-06-28T07:59:35.5943264Z      ^~~~~~~~~~~~~~~~~~~~~
```

File: mbedtls-compat.h (hunk 4 above)
Comment (azat) [reply mbedtls-compat.h:6]: - #1299

File: mbedtls-compat.h (hunk 5 above)
Comment (azat) [reply mbedtls-compat.h:5]: Missing `mbedtls/version.h`, fixed in #1299

**Comment by azat** [comment]
I've also extracted mbedTLS 3.0 fix into #1299

File: sample/becat.c (hunk 2 above)
Comment (azat) [reply sample/becat.c]: Fixed.

**Review by azat — APPROVED** [review]

**Review by azat — APPROVED** [review]

File: .github/workflows/linux.yml (hunk 3 above)
Comment (azat) [reply .github/workflows/linux.yml]: See 54078b30cbb92f19621c494b3255ef65e7a61a4c

**Comment by azat** [comment]
@lux01 many thanks! And special thanks for the mbedTLS 3.0 support!

**Comment by kloczek** [comment]
Any chance to make new release soon? 🤔

**Comment by azat** [comment]
>Any chance to make new release soon? thinking

Chances are high and you may help, by looking at issues from #1094 (for example by making CI stable or provide some fixes for existing issues if you are a C programmer and since you are using libevent this is likely true)

**Comment by lux01** [comment]
Thanks for all the comments and help in getting this merged :)

File: bufferevent_openssl.c (hunk 1 above)
Comment (azat) [reply bufferevent_openssl.c:262]: Also what I don't understand as of now, why the test does not fails in my env.
Compiled libevent with upstream openssl openssl/openssl@12e488367d
