### PR TITLE
Fix #1694, tested both on Firefox and Chrome

### LINKED ISSUE #1694: Websocket connection fails with 404 for request header "Connection: keep-alive, Upgrade" (Firefox)
I started playing around with the websocket server support in libevent and ran into the issue, that it is working when using Chromium, but it is failing when using Firefox 128 (Linux).

This issue is reproducible with the `ws-chat-server.c` example.

I tracked the issue down to the different "Connection" header values Chromium and Firefox are using:

- Chromium: `"Connection: Upgrade"`
- Firefox: `"Connection: keep-alive, Upgrade"`

The problem is the check for this header in `evws_new_session(...)`:

https://github.com/libevent/libevent/blob/7f23b5b5aa61f5496627c2651fd6d8185f34ffde/ws.c#L388-L390

I am uncertain, whether the "keep-alive" should be simply ignored or if this will require more changes.

### PR DESCRIPTION
**Pull request by widgetii**
Reimplemented our own evutil_ascii_strcasestr function (same as non-portable strcasestr)

Maybe in the future it's better to use internal strcasestr where possible

Fixes: https://github.com/libevent/libevent/issues/1694

### CODE REVIEW

File: include/event2/util.h [hunk 1]
```diff
@@ -717,6 +717,12 @@ int evutil_ascii_strcasecmp(const char *str1, const char *str2);
 EVENT2_EXPORT_SYMBOL
 int evutil_ascii_strncasecmp(const char *str1, const char *str2, size_t n);
 
+/** As strcasestr, but always searching substring in locale-independent
+    ASCII.  That's useful if you're handling data in ASCII-based protocols.
+ */
+EVENT2_EXPORT_SYMBOL
+const char* evutil_ascii_strcasestr(const char* s, const char *find);
```
Comment (azat) [inline include/event2/util.h:724]: Let's not export this function

File: ws.c [hunk 2]
```diff
@@ -386,7 +386,7 @@ evws_new_session(
 		goto error;
 
 	connection = evhttp_find_header(in_hdrs, "Connection");
-	if (connection == NULL || evutil_ascii_strcasecmp(connection, "Upgrade"))
```
Comment (azat) [inline ws.c:389]: Let's add a test for a new case

**Review by azat — COMMENTED** [review]
LGTM, can also adjust the commit message to include details i.e.

>ws: allow Upgrade in Connection header anywhere
>
>This will make it work for firefox, which uses "Connection: keep-alive, Upgrade"

File: include/event2/util.h (hunk 1 above)
Comment (widgetii) [reply include/event2/util.h:723]: Fixed

Comment (azat) [reply include/event2/util.h]: OK, let's move it into `util-internal.h`, this will be enough. Done

**Review by azat — APPROVED** [review]
