### PR TITLE
Fix unaligned access + missing frame length

### LINKED ISSUE #1518: Bug in make_ws_frame (ws.c), bug in get_ws_frame (ws.c)
It appears that the length is never written to the frame in the 8-byte case (>=65536).

https://github.com/libevent/libevent/blob/c9af024585e743f0eb1521b69165cab783982def/ws.c#L431

Also here we have two problems -- potentially unaligned access (not portable code, may fail on some arch's), and also using the wrong function to read the length `ntohs` just reads 2 bytes (unsigned short).  It should really be reading the full 64-bit value.

https://github.com/libevent/libevent/blob/c9af024585e743f0eb1521b69165cab783982def/ws.c#L231

### PR DESCRIPTION
**Pull request by cculianu**
Fixes #1518.

`get_ws_frame`:
  - had potentially unaligned access; fixed.
  - was not reading the full 8 bytes in the 64-bit case (was using the
    incorrect `htons`); fixed.

`make_ws_frame`:
  - wasn't writing the length in the 8-byte case.
  
Also switched both functions, plus the caller(s), to use `size_t` rather than `int` where appropriate.

### CODE REVIEW

**Comment by cculianu** [comment]
Pinging @widgetii , original submitter of this WebSocket implementation in #1322

**Review by widgetii — APPROVED** [review]

**Comment by cculianu** [comment]
Hmm CI not happy. Is the symbol `ntohll` not always available?

**Comment by cculianu** [comment]
I force-pushed a fix to not use the apparently not-always-available `htonll` and `ntohll` and instead swab the bytes manually using a `for()` loop.

CI should work now.

**Comment by cculianu** [comment]
I force-pushed again. Ok, done now.

File: ws.c [hunk 1]
```diff
@@ -221,17 +222,35 @@ get_ws_frame(unsigned char *in_buffer, int buf_len, unsigned char **payload_ptr,
...
 		if (buf_len < 10)
 			return INCOMPLETE_DATA;
-		payload_len = ntohs(*(uint64_t *)(in_buffer + 2));
-		pos += 8;
+		/* swab bytes from big endian to host byte order */
+		for (i = 56; i >= 0; i -= 8) {
+			tmp64 |= (uint64_t)in_buffer[pos++] << i;
+		}
+		if (tmp64 > (uint64_t)SIZE_MAX) {
+			/* Implementation limitation, we support up to size_t length.
```
Comment (cculianu) [inline ws.c:241]: Note that I am not sure what to do here -- we may want to define some limit to how big a WebSocket frame we accept.. On 32-bit systems it is limited by size_t, and on 64-bit systems it seems that it would be possible to have huge frames that don't fit in memory.

Actually on both 64-bit and 32-bit it would be possible to OOM a server by telling it a huge WebSocket frame follows, and then basically feeding it data, filling its buffers.

Maybe we want to define some limit like 1GiB or 100MiB or something?

Comment (widgetii) [reply ws.c:241]: I think it's a good idea, even 10MiB should be ok (I've never encountered such big frames before in real life)

Comment (cculianu) [reply ws.c:241]: Yeah to be honest I feel safer limiting it to 10MiB.  It can quickly become an exploit with anything bigger on a server with many sockets open.  I will add that to this PR as an additional commit, with a comment explaining the rationale.

Comment (cculianu) [reply ws.c]: Seems the CI job had some failures but they appear unrelated to this PR -- existing failures perhaps in `samples/becat.c` and only on some *BSD targets...

File: ws.c [hunk 2]
```diff
@@ -37,6 +38,11 @@
 #endif
 
 #define WS_UUID "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"
+/*
+ * We limit the size of received WS frames to 10 MiB,
+ * as a DoS prevention measure.
+ */
+static const size_t WS_MAX_RECV_FRAME_SZ = 10485760;
```
Comment (azat) [inline ws.c:45]: How about making it configurable? This can be made as a follow up PR

File: ws.c [hunk 3]
```diff
@@ -221,34 +226,54 @@ get_ws_frame(unsigned char *in_buffer, int buf_len, unsigned char **payload_ptr,
...
+		payload_len = ntohs(tmp16);
 		pos += 2;
 	} else if (length_field == 127) { /* msglen is 64bit */
+		int i;
+		uint64_t tmp64 = 0;
 		if (buf_len < 10)
 			return INCOMPLETE_DATA;
-		payload_len = ntohs(*(uint64_t *)(in_buffer + 2));
-		pos += 8;
+		/* swab bytes from big endian to host byte order */
```
Comment (azat) [inline ws.c:240]:
```suggestion
		/* swap bytes from big endian to host byte order */
```

File: ws.c [hunk 4]
```diff
@@ -221,34 +226,54 @@ get_ws_frame(unsigned char *in_buffer, int buf_len, unsigned char **payload_ptr,
...
+		for (i = 56; i >= 0; i -= 8) {
+			tmp64 |= (uint64_t)in_buffer[pos++] << i;
+		}
```
Comment (azat) [inline ws.c:243]: `bswap_64` can be used instead. It looks pretty standard, thought not sure about win32, but if it is not supported there it will be better to introduce a helper.

And we should not do the byte swap if we are a big endian platform

File: ws.c [hunk 5]
```diff
@@ -428,9 +453,13 @@ make_ws_frame(struct evbuffer *output, enum WebSocketFrameType frame_type,
 		header[pos++] = (len >> 8) & 0xFF; /* rightmost first */
 		header[pos++] = len & 0xFF;
 	} else {				 /* >2^16-1 */
-		header[pos++] = 127; /* 64 bit length */
-
-		pos += 8;
+		int i;
+		const uint64_t tmp64 = len;
+		header[pos++] = 127;            /* 64 bit length */
+		/* swab bytes from host byte order to big endian */
```
Comment (azat) [inline ws.c:459]: Same, what if we are on a big-endian system?

Comment (azat) [inline ws.c:459]:
```suggestion
		/* swap bytes from host byte order to big endian */
```

**Review by azat — CHANGES_REQUESTED** [review]

File: ws.c (hunk 2 above)
Comment (cculianu) [reply ws.c:45]: I would love to do this as a follow-up PR yes. I also agree making it configurable is a must.

File: ws.c (hunk 1 above)
Comment (cculianu) [reply ws.c]: The existing failures are in becat.c and seem to be related to missing header include or bsd lacking some name?  https://github.com/libevent/libevent/actions/runs/6533546637/job/17741718863?pr=1519#step:4:2248

File: ws.c (hunk 3 above)
Comment (cculianu) [reply ws.c:240]: The term swab is a real term used in programming and it usually refers to endian-swaps or other byte swapping. I'll change it though as per your request.  https://www.man7.org/linux/man-pages/man3/swab.3.html

File: ws.c (hunk 4 above)
Comment (cculianu) [reply ws.c:243]: - This code is a no-op on big-endian, since it is platform neutral to swap bytes in this way. On big endian the result will just be the original ordering.  Operator << and >> on C/C++ are defined in such a way such that they are arithmetic operators (increasing/decreasing by a power of 2). So, on big endian this is a no-op.
- `bswap_64` doesn't appear to exist on my macOS system.  I can do a follow-up PR with adding bswap_64 etc if you like ...

File: ws.c (hunk 5 above)
Comment (cculianu) [reply ws.c:459]: It's a no-op there.

Although it does eat cycles.

Do you have a compiler-define that defines big endian? I can `#ifdef` the code out then if the CPU cycle eating for a no-op is an issue for you on big endian.

Comment (cculianu) [reply ws.c]: I just checked there is no project-wide `#define`  regarding endian-ness, nor is there anything in `event2/event-config.h`.  The closest thing is a per-file compile options applied to `sha1.c` that defines `LITTLE_ENDIAN=1` or `BIG_ENDIAN=1` which is required by that file to compile.

So there is no way to test endianness from the sources -- not without modification of `CMakeLists.txt` and/or the autoconf build system.

I can add such a modification to this PR if you like, and then `#ifdef` out this code on big-endian.  Or we can leave it as-is (since it's harmless) and do the work in a follow-up PR to add this to the build system for `ws.c`, etc.

File: ws.c (hunk 1 above)
Comment (azat) [reply ws.c]: I don't see any failures of becat. Let's simply forget about this.

File: ws.c (hunk 4 above)
Comment (azat) [reply ws.c:243]: Oh, sorry, I've just read the comment, not the code, and I missed that you are simply reading from the `char *` as network byte order to host byte order. So let's update the comment then.

But the code is wrong, `(uint64_t)in_buffer[pos++]` will read `uint64` from the `in_buffer` always, while you need to read only one byte - `(uint64_t)(data[pos++] & 0xff)`

Also let's use `CHAR_BIT` instead of `8`, and instead of `56` something like `8 * (CHAR_BIT - 1)`. Or, actually I guess we cannot use `sizeof(uint64_t)`, since it should be `8` on any platform?

And let's introduce helper for this and write a unit test.

File: ws.c (hunk 3 above)
Comment (azat) [reply ws.c]: Oh, sorry, haven't heard it before. Thank you for the link. And it is OK to use `swab` here of course.

File: ws.c (hunk 5 above)
Comment (azat) [reply ws.c]: It is OK to keep this code as is (but if you will replace some constant in the decoding loop, then let's replace them here as well).

File: ws.c (hunk 4 above)
Comment (cculianu) [reply ws.c:243]: > sizeof(uint64_t), since it should be 8 on any platform?

Well .. yes and no.  Yes I believe these are specified to be *exactly* 64-bits.. now.. if `CHAR_BIT` differs.. you are in for a surprising time!  Since `sizeof(uint64_t)` might not be 8.. it will instead be something like `(64/CHAR_BIT)` 

Hmm.. yes I see what you are saying about the constants.  

Remember this though: POSIX mandates `CHAR_BIT == 8.` I know you compile for technically-non-POSIX systems (win32) -- but even there CHAR_BIT is 8. I think you should make it a project assumption that CHAR_BIT == 8 and require that.  I suspect more than just `ws.c` would explode in that case if CHAR_BIT != 8.  


---

So: Really.. What happens on a hypothetical machine that has CHAT_BIT not set to 8?  Remember on such a machine also `sizeof(whatever)` is affected because `sizeof` is defined as returning the number of characters. 

- If `CHAR_BIT == 6`, for instance, then we would need to adjust this loop.. as you suggested... to be based off of `CHAR_BIT` for the initial conditions and loop decrement.. and things should work.
- If `CHAR_BIT == 12` we can't even do `& 0xff` as you suggested since that would be wrong! We would need to be doing `& 0x7ff` here!  
- Actually in all cases you want to *not* be doing ANY `& 0xff` <-- this has, baked-in, an assumption about `CHAR_BIT == 8` :)

You see what I'm saying?  This project already is assuming `CHAR_BIT == 8` implicitly or even explicitly everywhere. 

I must say this again -- you ought to make it a project assumption that `CHAR_BIT == 8`. `ws.c` already would fail on such a system if you scroll up and down in the file it already assumes CHAR_BIT == 8 in code I didn't write in the file.

So long story short: Yes, I can adjust it as you say -- but I really do think this project should assume `CHAR_BIT == 8` for its own sanity..

Comment (cculianu) [reply ws.c:243]: ... Also remember the protocol is specifying that exactly 8 * 8-bit-bytes of data are coming in off the wire here.. literal constants like 8 and 64 are baked-in to the protocol already.. so there's that too.

Comment (cculianu) [reply ws.c:243]: Now.. I could be persuaded to use `CHAR_BIT` here for *readability*... to make people reading this code more easily understand *intent* here.

.. but this project really does not support `CHAR_BIT != 8`, I can assure you of that..

Comment (azat) [reply ws.c:243]: Yes, I see your points, thanks. So let's just add a check into cmake & autotools that `CHAR_BIT` is 8, and done with this.

File: ws.c (hunk 5 above)
Comment (cculianu) [reply ws.c]: Hey sorry for belated reply -- I got caught up in some other commitments. I will update this PR this weekend hopefully or sometime next week worst case, I hope!

File: ws.c [hunk 6]
```diff
@@ -221,34 +226,54 @@ get_ws_frame(unsigned char *in_buffer, int buf_len, unsigned char **payload_ptr,
...
 	} else if (length_field == 127) { /* msglen is 64bit */
+		int i;
+		uint64_t tmp64 = 0;
 		if (buf_len < 10)
 			return INCOMPLETE_DATA;
-		payload_len = ntohs(*(uint64_t *)(in_buffer + 2));
-		pos += 8;
+		/* swap bytes from big endian to host byte order */
+		for (i = 56; i >= 0; i -= 8) {
+			tmp64 |= (uint64_t)in_buffer[pos++] << i;
```
Comment (azat) [inline ws.c:242]: @cculianu sorry for the delay

What about this comment?

> But the code is wrong, (uint64_t)in_buffer[pos++] will read uint64 from the in_buffer always, while you need to read only one byte - (uint64_t)(data[pos++] & 0xff)

Comment (azat) [reply ws.c:242]: Also can you please add a regression test for this, AFAIU it should be pretty easy, just use bigger messages

Comment (azat) [reply ws.c:242]: Nevermind, the problem exists only if `in_buffer` was `char *`, it is ok for `unsigned char *`.

```
(gdb) p/x (char)0xde<<8
$4 = 0xffffde00
(gdb) p/x (unsigned char)0xde<<8
$5 = 0xde00

```

**Review by azat — APPROVED** [review]

**Comment by azat** [comment]
@cculianu OK, I've merged as-is, but can you please continue on this:
- add unit test
- make upper bound configurable
